CC=gcc #compiler
TARGET=main #target file name

all: main.o bst.o
	$(CC) main.c bst.c -o $(TARGET)

clean: 
	rm *.o $(TARGET)

// Execute below to compile and clean
// make -f Makefile all
// make -f Makefile clean
